### ISSUE TITLE
Use nodeimu as a dependency

### ISSUE THREAD

**Issue by rbartoli** [rupnikj/nodeimu#7]
Hi Jan,

Thanks a lot for providing this package - it's extremely useful to get started with the Sense HAT and Node.js.

I'd like to create a simple app to store the data from the sensors on the Sense HAT in MongoDB and stream the latest reading using socket.io. I modified a clone of this repository with no issues (I was just playing) and everything has been working correctly.

I've then created a new node package (to start the project from scratch) and added `nodeimu` as a dependency with `npm install --save nodeimu` as I saw that the project has been published on npm. 

However when I do `npm install` in the new project, I get the following error:

``` bash
make: Entering directory '/home/pi/nodeimu-server/node_modules/nodeimu/build'
  CXX(target) Release/obj.target/NodeIMU/addon.o
In file included from ../nodeimu.h:8:0,
                 from ../addon.cpp:2:
../../nan/nan.h:602:20: error: variable or field ‘AddGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback
                    ^
../../nan/nan.h:602:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback
       ^
../../nan/nan.h:603:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../../nan/nan.h:608:20: error: variable or field ‘RemoveGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback) {
                    ^
../../nan/nan.h:608:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback) {
       ^
../../nan/nan.h:613:20: error: variable or field ‘AddGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback
                    ^
../../nan/nan.h:613:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback
       ^
../../nan/nan.h:614:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../../nan/nan.h:619:20: error: variable or field ‘RemoveGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback) {
                    ^
../../nan/nan.h:619:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback) {
       ^
NodeIMU.target.mk:116: recipe for target 'Release/obj.target/NodeIMU/addon.o' failed
make: *** [Release/obj.target/NodeIMU/addon.o] Error 1
make: Leaving directory '/home/pi/nodeimu-server/node_modules/nodeimu/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pi/.nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.4.9-v7+
gyp ERR! command "/home/pi/.nvm/versions/node/v6.2.0/bin/node" "/home/pi/.nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/nodeimu-server/node_modules/nodeimu
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.3.1
```

I have `node-gyp` installed globally.
I was wondering if you had any idea.

Thanks!

**Comment by rupnikj** [comment]
What version of node-gyp and node are you using? It might be related to nodejs 6.0

**Comment by rbartoli** [comment]
I'm using:

``` bash
node -v v6.2.0
node-gyp -v v3.3.1
```

However they do work on the `nodeimu` repository itself.

**Comment by rbartoli** [comment]
Apparently removing the globally installed version of `node-gyp` fixed the issues and everything is building properly now. Thanks.

**Comment by rupnikj** [comment]
Great:)
